change the job

diff --git a/.github/workflows/build.blocks.yml b/.github/workflows/build.blocks.yml
--- a/.github/workflows/build.blocks.yml
+++ b/.github/workflows/build.blocks.yml
@@ -12,4 +12,8 @@ jobs:
     steps:
       - name: say goodbye
         run: |
+          echo " this fail message"
+          exit 1
+      - name: say goodbye
+        run: |
           echo "Hello it's good bye message"
